@echo off
echo Removing old virtual environment...
if exist .venv rmdir /s /q .venv
echo Creating virtual environment...
python -m venv .venv
echo Activating virtual environment...
call .venv\Scripts\activate
echo Installing dependencies...
python -m pip install --upgrade pip
python -m pip install -r requirements.txt
echo Starting backend...
python -m uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
pause
