@echo off
echo Creating virtual environment...
python -m venv .venv
echo Activating virtual environment...
call .venv\Scripts\activate
echo Installing dependencies...
pip install -r requirements.txt
echo Starting backend...
uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
pause
